plugins {
	id 'net.fabricmc.fabric-loom'
	id 'maven-publish'
}

version = '1.1.0+mc26.2'
group = 'liquidui'

base {
	archivesName = 'liquid-ui-library'
}

repositories {
}

loom {
	runs {
		client {
			displayName = "Liquid UI Library Client"
		}
		server {
			displayName = "Liquid UI Library Server"
		}
	}
	mods {
		"liquid_ui_library" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}
